services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
